apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
bases:
  - ../../base
replicas:
  - name: pacman-kikd
    count: 1
images:
  - name: lordofthejars/pacman-kikd
    newTag: latest
commonLabels:
  environment: dev
patchesStrategicMerge:
  - deployment-patch.yaml
