apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
bases:
  - ../../base
replicas:
  - name: pacman-kikd
    count: 2
images:
  - name: lordofthejars/pacman-kikd
    newTag: v1.0.0
commonLabels:
  environment: staging
patchesStrategicMerge:
  - deployment-patch.yaml
