apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
bases:
  - ../../base
replicas:
  - name: pacman-kikd
    count: 3
images:
  - name: lordofthejars/pacman-kikd
    newTag: v1.0.0
commonLabels:
  environment: prod
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
