apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
replicas:
  - name: pacman-kikd
    count: 3
images:
  - name: lordofthejars/pacman-kikd
    newTag: v1.0.0
labels:
  - pairs:
      environment: prod
patches:
  - path: deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: pacman-kikd
