apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pacman
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/managed-by: kustomize