apiVersion: v1
kind: Service
metadata:
  name: pacman-kikd
  namespace: pacman
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: pacman-kikd
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP